# -*- coding: utf-8 -*-
"""Scraping_Muhammad_Azhar_Fikri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6wcFYXh28nONPbjtK7oif9X2UuLLPoq
"""

!pip install google-play-scraper
from google_play_scraper import app, reviews, Sort, reviews_all

import pandas as pd
import csv

from google_play_scraper import reviews, Sort

scrapreview, _ = reviews(  # ← ambil hanya review-nya
    'com.tokopedia.tkpd',      # ID aplikasi Notion
    lang='id',                 # Bahasa Indonesia
    country='id',              # Negara Indonesia
    sort=Sort.MOST_RELEVANT,   # Urutkan berdasarkan ulasan paling relevan
    count=25000                # Jumlah ulasan yang diambil
)

app_reviews_df = pd.DataFrame(scrapreview)
app_reviews_df.shape
app_reviews_df.head()
app_reviews_df.to_csv('ulasan_aplikasi.csv', index=False)

# Membuat DataFrame dari hasil scrapreview
app_reviews_df = pd.DataFrame(scrapreview)

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_ulasan, jumlah_kolom = app_reviews_df.shape

# Menampilkan lima baris pertama dari DataFrame app_reviews_df
app_reviews_df.head()

# Menampilkan informasi tentang DataFrame app_reviews_df
app_reviews_df.info()